---
- hosts: all
  become: true
  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        when: ansible_facts['os_family'] == "Debian"
        update_cache: yes
    - name: Start abd enable Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes




