---
- name: Shutdown only Ubuntu instances created from this playbook
  hosts: localhost
  connection: local
  vars_files:
    - /home/ubuntu/ansible-playbooks/ec2/vars/main.yml
  tasks:
    - name: Stop Ubuntu instances created by this playbook (using tags/names)
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        filters:
          tag:Name: "{{ item.name }}"
        state: stopped
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
          ansible.builtin.command: /sbin/shutdown -t now
      loop: "{{ ec2_instance }}"
      when: #"'ubuntu' in item.name"
        ansible_facts['os.family'] == "Debian"

