---
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "{{ item.name }}"
    key_name: "Ansible_key"
    region: "{{ region }}"
    instance_type: "{{ type }}"
    security_groups: "{{ group }}"
    image_id: "{{ item.image }}"
    wait: yes
    state: present
    aws_access_key: "{{ ec2_access_key }}"  # From vault
    aws_secret_key: "{{ ec2_secret_key }}"  # From vault
    network:
      assign_public_ip: true
  loop: "{{ ec2_instance }}"

